# Generated by Django 6.0.5 on 2026-07-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0002_notificacion_tiponotificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoBilletera',
            fields=[
                ('pago', models.OneToOneField(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pago_billetera', serialize=False, to='pagos.pago')),
                ('billetera', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Pago con Billetera',
                'verbose_name_plural': 'Pagos con Billetera',
                'db_table': 'pagos_billetera',
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('pago', models.OneToOneField(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pago_tarjeta', serialize=False, to='pagos.pago')),
                ('numero_tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Pago con Tarjeta',
                'verbose_name_plural': 'Pagos con Tarjeta',
                'db_table': 'pagos_tarjeta',
            },
        ),
        migrations.AlterModelOptions(
            name='estadopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de pago', 'verbose_name_plural': 'Estados de pagos'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Método de pago', 'verbose_name_plural': 'Métodos de pago'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='tipometodopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de método de pago', 'verbose_name_plural': 'Tipos de métodos de pago'},
        ),
        migrations.AlterField(
            model_name='estadopago',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='metodos', to='pagos.tipometodopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.ForeignKey(db_column='estado_pago_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='pagos.estadopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='pagos.metodopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='tipometodopago',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
