# Generated by Django 6.0.5 on 2026-06-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_usuario_apellido_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='rol_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='authentication.rol'),
        ),
    ]
