# Generated by Django 6.0.5 on 2026-07-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanchaBasket',
            fields=[
                ('cancha', models.OneToOneField(db_column='cancha_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cancha_basket', serialize=False, to='canchas.cancha')),
                ('canastas_profesional', models.BooleanField(default=False)),
                ('marcador_digital', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cancha de Basquetbol',
                'verbose_name_plural': 'Canchas de Basquetbol',
                'db_table': 'canchas_basket',
            },
        ),
        migrations.CreateModel(
            name='CanchaFutbol',
            fields=[
                ('cancha', models.OneToOneField(db_column='cancha_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cancha_futbol', serialize=False, to='canchas.cancha')),
                ('tipo_cesped', models.CharField(blank=True, max_length=50, null=True)),
                ('arcos_profesional', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cancha de Fútbol',
                'verbose_name_plural': 'Canchas de Fútbol',
                'db_table': 'canchas_futbol',
            },
        ),
        migrations.CreateModel(
            name='CanchaValley',
            fields=[
                ('cancha', models.OneToOneField(db_column='cancha_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cancha_valley', serialize=False, to='canchas.cancha')),
                ('tipo_superficie', models.CharField(blank=True, max_length=50, null=True)),
                ('altura_red', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Cancha de Voleibol',
                'verbose_name_plural': 'Canchas de Voleibol',
                'db_table': 'canchas_valley',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='estadocancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de cancha', 'verbose_name_plural': 'Estados de canchas'},
        ),
        migrations.AlterModelOptions(
            name='horariobloqueado',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Horario bloqueado', 'verbose_name_plural': 'Horarios bloqueados'},
        ),
        migrations.AlterModelOptions(
            name='regla',
            options={'ordering': ['nombre'], 'verbose_name': 'Regla', 'verbose_name_plural': 'Reglas'},
        ),
        migrations.AlterField(
            model_name='cancha',
            name='estado',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='canchas', to='canchas.estadocancha'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='reglas',
            field=models.ManyToManyField(db_table='canchas_reglas', related_name='canchas', to='canchas.regla'),
        ),
        migrations.AlterField(
            model_name='estadocancha',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='horariobloqueado',
            name='cancha',
            field=models.ForeignKey(db_column='cancha_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='regla',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='HorarioManana',
            fields=[
                ('horario', models.OneToOneField(db_column='horario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='horario_manana', serialize=False, to='canchas.horario')),
            ],
            options={
                'verbose_name': 'Horario Mañana',
                'verbose_name_plural': 'Horarios Mañana',
                'db_table': 'horarios_manana',
            },
        ),
        migrations.CreateModel(
            name='HorarioNoche',
            fields=[
                ('horario', models.OneToOneField(db_column='horario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='horario_noche', serialize=False, to='canchas.horario')),
            ],
            options={
                'verbose_name': 'Horario Noche',
                'verbose_name_plural': 'Horarios Noche',
                'db_table': 'horarios_noche',
            },
        ),
        migrations.CreateModel(
            name='HorarioTarde',
            fields=[
                ('horario', models.OneToOneField(db_column='horario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='horario_tarde', serialize=False, to='canchas.horario')),
            ],
            options={
                'verbose_name': 'Horario Tarde',
                'verbose_name_plural': 'Horarios Tarde',
                'db_table': 'horarios_tarde',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='cancha',
            field=models.ForeignKey(db_column='cancha_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='canchas.cancha'),
        ),
    ]
