# Generated by Django 6.0.5 on 2026-06-15 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estados_reservas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(db_column='cancha_id', on_delete=django.db.models.deletion.RESTRICT, to='canchas.cancha')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, to='reservas.estadoreserva')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
