# Generated by Django 6.0.5 on 2026-07-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_canchabasket_canchafutbol_canchavalley_horario_and_more'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de notificación',
                'verbose_name_plural': 'Tipos de notificaciones',
                'db_table': 'tipos_notificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='estadoreserva',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de reserva', 'verbose_name_plural': 'Estados de reservas'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='estadoreserva',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(db_column='cancha_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='reservas.estadoreserva'),
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('notificacion', models.OneToOneField(db_column='notificacion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notificacion_email', serialize=False, to='reservas.notificacion')),
                ('destinatario', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Notificación Email',
                'verbose_name_plural': 'Notificaciones Email',
                'db_table': 'notificaciones_email',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('notificacion', models.OneToOneField(db_column='notificacion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notificacion_push', serialize=False, to='reservas.notificacion')),
                ('token_dispositivo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Notificación Push',
                'verbose_name_plural': 'Notificaciones Push',
                'db_table': 'notificaciones_push',
            },
        ),
        migrations.CreateModel(
            name='NotificacionSMS',
            fields=[
                ('notificacion', models.OneToOneField(db_column='notificacion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notificacion_sms', serialize=False, to='reservas.notificacion')),
                ('numero_telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Notificación SMS',
                'verbose_name_plural': 'Notificaciones SMS',
                'db_table': 'notificaciones_sms',
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='notificaciones', to='reservas.tiponotificacion'),
        ),
    ]
