# Generated by Django 6.0.5 on 2026-06-23 01:19

import django.db.models.deletion
import decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ReservaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total_general', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas_grupos',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.reservagrupo'),
        ),
    ]
