# Generated by Django 6.0.6 on 2026-07-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_notificacion_tiponotificacion_and_more'),
        ('reservas', '0002_reserva_duracion_minutos_reserva_precio_por_hora_and_more'),
    ]

    operations = [
    ]
